services:
  db:
    image: postgres:15
    container_name: user-crud-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bilashbi
      POSTGRES_DB: user-crud
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: user-crud-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: bilashbi
      DB_DATABASE: user-crud
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: user-crud-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
